<?php

namespace App\Http\Requests\Accounting;

use Illuminate\Foundation\Http\FormRequest;

class StoreInvoiceRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'customer_id' => 'nullable|exists:customers,id',
            'customer_name' => 'nullable|string|max:255',
            'customer_address' => 'nullable|string|max:255',
            'customer_email' => 'nullable|string|email|max:255',
            'customer_contact' => ['nullable', 'string', 'regex:/^(09|\+639|639)\d{9}$/'],
            'payment_method' => 'required|string',
            'payment_type' => 'nullable|string|in:full,downpayment',
            'amount_received' => 'nullable|numeric|min:0',
            'due_date' => 'nullable|date',
            'travel_date' => 'nullable|date',
            'arrival_datetime' => 'nullable|date',
            'departure_datetime' => 'nullable|date',
            'pickup_location' => 'nullable|string|max:255',
            'tour_code' => 'nullable|string|max:255',
            'pax_count' => 'nullable|integer|min:1',
            'items' => 'required|array|min:1',
            'items.*.service_id' => 'nullable|required_without:items.*.item_name|exists:services,id',
            'items.*.passport_case_id' => 'nullable|integer|distinct|exists:passport_cases,id',
            'items.*.item_name' => 'nullable|required_without:items.*.service_id|string|max:255',
            'items.*.service_type' => 'nullable|string|max:80',
            'items.*.item_description' => 'nullable|string',
            'items.*.description' => 'nullable|string',
            'items.*.item_metadata' => 'nullable|array',
            'items.*.item_metadata.rate_plan_id' => 'nullable|integer|exists:charter_rate_plans,id',
            'items.*.item_metadata.program_id' => 'nullable|integer|exists:educational_tour_programs,id',
            'items.*.item_metadata.starts_at' => 'nullable|date',
            'items.*.item_metadata.ends_at' => 'nullable|date|after:items.*.item_metadata.starts_at',
            'items.*.item_metadata.estimated_kilometers' => 'nullable|numeric|min:0|max:10000',
            'items.*.item_metadata.passenger_count' => 'nullable|integer|min:1|max:5000',
            'items.*.item_metadata.pickup_location' => 'nullable|string|max:255',
            'items.*.item_metadata.destination' => 'nullable|string|max:255',
            'items.*.item_metadata.stops' => 'nullable',
            'items.*.item_metadata.buses_required' => 'nullable|integer|min:1|max:100',
            'items.*.item_metadata.requested_units' => 'nullable|integer|min:1|max:100',
            'items.*.item_metadata.bus_assignments' => 'nullable|array|max:100',
            'items.*.item_metadata.bus_assignments.*.bus_id' => 'required_with:items.*.item_metadata.bus_assignments|integer|exists:buses,id|distinct',
            'items.*.item_metadata.bus_assignments.*.driver_id' => 'nullable|integer|exists:users,id|distinct',
            'items.*.item_metadata.assignments' => 'nullable|array|max:100',
            'items.*.item_metadata.assignments.*.bus_id' => 'required_with:items.*.item_metadata.assignments|integer|exists:buses,id|distinct',
            'items.*.item_metadata.assignments.*.driver_id' => 'required_with:items.*.item_metadata.assignments|integer|exists:users,id|distinct',
            'items.*.item_metadata.assignments.*.planned_passengers' => 'required_with:items.*.item_metadata.assignments|integer|min:1',
            'items.*.item_metadata.booking_mode' => 'nullable|in:entire_vehicle,selected_seats',
            'items.*.item_metadata.selected_seats' => 'nullable|array|max:5000',
            'items.*.item_metadata.selected_seats.*' => 'string|max:80|distinct',
            'items.*.item_metadata.passengers' => 'nullable|array|max:5000',
            'items.*.item_metadata.passengers.*.first_name' => 'required_with:items.*.item_metadata.passengers|string|max:100',
            'items.*.item_metadata.passengers.*.last_name' => 'required_with:items.*.item_metadata.passengers|string|max:100',
            'items.*.item_metadata.passengers.*.role' => 'nullable|in:student,adult,child,tour_guide',
            'items.*.item_metadata.passengers.*.seat_code' => 'nullable|string|max:80|distinct',
            'items.*.item_metadata.passengers.*.date_of_birth' => 'nullable|date|before_or_equal:today',
            'items.*.item_metadata.passengers.*.passport_number' => 'nullable|string|max:100',
            'items.*.item_metadata.passengers.*.dietary_restrictions' => 'nullable|string|max:255',
            'items.*.item_metadata.passengers.*.emergency_contact' => 'nullable|string|max:255',
            'items.*.item_metadata.passengers.*.special_needs' => 'nullable|string|max:1000',
            'items.*.item_metadata.school_name' => 'nullable|string|max:255',
            'items.*.item_metadata.contact_person' => 'nullable|string|max:255',
            'items.*.item_metadata.contact_email' => 'nullable|email|max:255',
            'items.*.item_metadata.contact_number' => 'nullable|string|max:30',
            'items.*.item_metadata.grade_level' => 'nullable|string|max:100',
            'items.*.item_metadata.student_count' => 'nullable|integer|min:1|max:5000',
            'items.*.item_metadata.tour_guide_count' => 'nullable|integer|min:0|max:1000',
            'items.*.item_metadata.chaperone_count' => 'nullable|integer|min:0|max:1000',
            'items.*.item_metadata.operations_notes' => 'nullable|string|max:3000',
            'items.*.item_metadata.inclusions' => 'nullable|array',
            'items.*.item_metadata.inclusions.*' => 'string|max:255',
            'items.*.item_metadata.exclusions' => 'nullable|array',
            'items.*.item_metadata.exclusions.*' => 'string|max:255',
            'items.*.item_metadata.itinerary' => 'nullable|array',
            'items.*.quantity' => 'required|integer|min:1',
            'items.*.unit_price' => 'nullable|numeric|min:0',
            'items.*.adults' => 'nullable|integer|min:0',
            'items.*.children' => 'nullable|integer|min:0',
            'items.*.adult_price' => 'nullable|numeric|min:0',
            'items.*.child_price' => 'nullable|numeric|min:0',
            'items.*.service_date' => 'nullable|date',
            'items.*.destination' => 'nullable|string',
            'notes' => 'nullable|string',
            'bus_id' => 'nullable|integer|exists:buses,id',
            'driver_id' => 'nullable|integer|exists:users,id',
            'bus_assignments' => 'nullable|array',
            'bus_assignments.*.bus_id' => 'nullable|integer',
            'bus_assignments.*.driver_id' => 'nullable|integer',
            'seat_map' => 'nullable|array',
            'tax_rate' => 'nullable|numeric|min:0|max:1',
            'custom_transaction_detail' => 'nullable|array',
            'custom_transaction_detail.passport_case_id' => 'nullable|integer|exists:passport_cases,id',
            'custom_transaction_detail.category' => 'required_with:custom_transaction_detail|string|max:100',
            'custom_transaction_detail.vehicle_type' => 'nullable|string|max:100',
            'custom_transaction_detail.route' => 'nullable|string|max:255',
            'custom_transaction_detail.rental_days' => 'nullable|integer|min:1',
            'custom_transaction_detail.plate_number' => 'nullable|string|max:50',
            'custom_transaction_detail.inclusion_driver' => 'nullable|boolean',
            'custom_transaction_detail.inclusion_fuel' => 'nullable|boolean',
            'custom_transaction_detail.inclusion_toll' => 'nullable|boolean',
            'custom_transaction_detail.inclusion_insurance' => 'nullable|boolean',
            'custom_transaction_detail.school_name' => 'nullable|string|max:255',
            'custom_transaction_detail.grade_level' => 'nullable|string|max:100',
            'custom_transaction_detail.expected_pax' => 'nullable|integer|min:0',
            'custom_transaction_detail.itinerary_stops' => 'nullable|string',
            'custom_transaction_detail.edu_inclusion_meals' => 'nullable|boolean',
            'custom_transaction_detail.edu_inclusion_coordinator' => 'nullable|boolean',
            'custom_transaction_detail.edu_inclusion_insurance' => 'nullable|boolean',
            'custom_transaction_detail.edu_inclusion_tshirt' => 'nullable|boolean',
            'custom_transaction_detail.destination' => 'nullable|string|max:255',
            'custom_transaction_detail.accommodation_type' => 'nullable|string|max:100',
            'custom_transaction_detail.visa_country' => 'nullable|string|max:100',
            'custom_transaction_detail.visa_type' => 'nullable|string|max:100',
            'custom_transaction_detail.visa_req_passport' => 'nullable|boolean',
            'custom_transaction_detail.visa_req_photo' => 'nullable|boolean',
            'custom_transaction_detail.visa_req_bank_cert' => 'nullable|boolean',
            'custom_transaction_detail.visa_req_itr' => 'nullable|boolean',
            'custom_transaction_detail.visa_req_birth_cert' => 'nullable|boolean',
            'custom_transaction_detail.joiner_tour_code' => 'nullable|string|max:255',
            'custom_transaction_detail.booking_type' => 'nullable|string|max:100',
            'custom_transaction_detail.booking_reference_code' => 'nullable|string|max:255',
            'custom_transaction_detail.booking_details' => 'nullable|string',
            'custom_transaction_detail.category_meta' => 'nullable|array',
            'custom_transaction_detail.additional_remarks' => 'nullable|string',
            'itinerary' => 'nullable|array',
            'itinerary.*.day_number' => 'required_with:itinerary|integer|min:1',
            'itinerary.*.date' => 'nullable|date',
            'itinerary.*.location' => 'nullable|string|max:255',
            'itinerary.*.activity_description' => 'nullable|string',
            'itinerary.*.meal_plan' => 'nullable|string|max:255',
            'itinerary.*.accommodation_name' => 'nullable|string|max:255',
            'itinerary.*.check_in_time' => 'nullable|string|max:20',
            'itinerary.*.check_out_time' => 'nullable|string|max:20',
            'passengers' => 'nullable|array',
            'passengers.*.first_name' => 'required_with:passengers|string|max:255',
            'passengers.*.last_name' => 'required_with:passengers|string|max:255',
            'passengers.*.seat_code' => 'nullable|string|max:50',
            'passengers.*.passenger_type' => 'nullable|string|in:adult,child',
            'passengers.*.date_of_birth' => 'nullable|date',
            'passengers.*.passport_number' => 'nullable|string|max:100',
            'passengers.*.dietary_restrictions' => 'nullable|string|max:255',
            'passengers.*.emergency_contact' => 'nullable|string|max:255',
            'passengers.*.special_needs' => 'nullable|string',
        ];
    }

    public function messages(): array
    {
        return [
            'customer_contact.regex' => 'The contact number must be a valid Philippine mobile number.',
            'customer_email.email' => 'The email address must be a valid email format.',
            'items.*.item_metadata.bus_assignments.*.bus_id.required_with' => 'Select a fleet bus for every requested charter unit before checkout.',
            'items.*.item_metadata.bus_assignments.*.bus_id.exists' => 'One of the selected charter buses is no longer available. Refresh the fleet list and choose another bus.',
            'items.*.item_metadata.assignments.*.bus_id.required_with' => 'Select a fleet bus for every travel assignment before checkout.',
            'items.*.item_metadata.assignments.*.driver_id.required_with' => 'Select a driver for every travel assignment before checkout.',
        ];
    }
}
