import { useState, useMemo, useEffect, useRef } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useAuth } from '../../context/AuthContext';
import {
  LuUsers,
  LuBanknote,
  LuGlobe,
  LuFileText,
  LuBus,
  LuDownload,
  LuFileSpreadsheet,
  LuChevronLeft,
  LuChevronRight,
  LuTicket
} from 'react-icons/lu';


import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';
import { loadLogoAsBase64 } from '../../utils/pdfHelpers';
import { dashboardApi } from '../../api/dashboards';
import { tripTicketApi, cashBudgetApi } from '../../api/operations';
import { fleetApi } from '../../api/fleet';
import toast from 'react-hot-toast';
import { LoadingScreen } from '../../components/ui';


// topDrivers removed










export default function AdminDashboard() {
  const { user } = useAuth();

  // ── Live API Queries ──────────────────────────────────────────────────────
  const { data: dashboardData, isLoading, error } = useQuery({
    queryKey: ['dashboard', 'admin'],
    queryFn: dashboardApi.getAdmin,
    staleTime: 1000 * 60 * 2,
  });

  const { data: ticketsRaw } = useQuery({
    queryKey: ['trip-tickets-admin'],
    queryFn: tripTicketApi.getAll,
    staleTime: 1000 * 60 * 2,
  });

  const { data: busesRaw } = useQuery({
    queryKey: ['buses-admin'],
    queryFn: () => fleetApi.list({ per_page: 100 }).then(r => r.data),
    staleTime: 1000 * 60 * 5,
  });

  const { data: cashBudgets = [], refetch: refetchCashBudgets } = useQuery({
    queryKey: ['cash-budgets-list'],
    queryFn: () => cashBudgetApi.getAll(),
    staleTime: 1000 * 60 * 2,
  });

  const tickets = (ticketsRaw as any[]) ?? [];
  const buses = (busesRaw as any)?.data ?? [];

  const isApprover = user && ['super_admin', 'executive_vice_president', 'accounting_executive'].includes(user.role);

  const pendingBudgets = useMemo(() => {
    return cashBudgets.filter((b: any) => b.status === 'pending_accounting');
  }, [cashBudgets]);

  const busesUnderMaintenance = useMemo(() => {
    return buses.filter((b: any) => b.status === 'under_maintenance');
  }, [buses]);


  const exportToPDF = async (title: string, data: any[]) => {
    try {
      const doc = new jsPDF();

      // Add Logo (loaded as base64 to work in all environments including production)
      const logoBase64 = await loadLogoAsBase64('/JVDlogo-removebg-preview.png');
      if (logoBase64) {
        doc.addImage(logoBase64, 'PNG', 160, 10, 35, 35);
      }

      // Header Section
      doc.setFontSize(22);
      doc.setTextColor(30, 64, 175);
      doc.setFont("helvetica", "bold");
      doc.text("JVD MANAGEMENT SYSTEM", 14, 25);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.setFont("helvetica", "normal");
      doc.text("INTERNAL ORGANIZATIONAL REPORT", 14, 32);

      // Company Address (Mock)
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("UNIT 6 -Aryanna Village Center Brgy 175. Susano Road Camarin, Caloocan City, Caloocan, Philippines", 14, 37);
      doc.text("Contact: +63 976 - 4711 - 294", 14, 41);
      doc.text("Tel: 02 - 82938068", 14, 45);

      doc.setDrawColor(226, 232, 240);
      doc.line(14, 47, 196, 47);

      // Report Title & Meta
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.setFont("helvetica", "bold");
      doc.text(`Official Report: ${title}`, 14, 55);

      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated by: ${user?.first_name} ${user?.last_name || 'Authorized Personnel'}`, 14, 62);
      doc.text(`Date: ${new Date().toLocaleString()}`, 14, 67);
      doc.text(`Reference ID: JVD-REF-${Math.floor(100000 + Math.random() * 900000)}`, 14, 72);



      // Main Data Table
      autoTable(doc, {
        head: [Object.keys(data[0]).map(k => k.toUpperCase())],
        body: data.map(obj =>
          Object.values(obj).map(val =>
            typeof val === 'string' ? val.replace(/PHP /g, 'PHP ').replace(/₱/g, 'PHP ') : val
          )
        ) as any,
        startY: 80,
        theme: 'grid',
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 10,
          cellPadding: 4
        },
        bodyStyles: {
          fontSize: 9,
          cellPadding: 3,
          fillColor: false // Transparent to show watermark behind
        },
        alternateRowStyles: {
          fillColor: false // Transparent to show watermark behind
        },
        margin: { top: 80 }
      });

      // Signature Section
      let finalY = 240; // Default fallback position
      try {
        if ((doc as any).lastAutoTable && (doc as any).lastAutoTable.finalY) {
          finalY = (doc as any).lastAutoTable.finalY + 20;
        }
      } catch (e) {
        console.warn("Could not determine table end, using default Y");
      }

      if (finalY < 270) {
        doc.setDrawColor(200);
        doc.line(14, finalY, 70, finalY);
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text("Authorized Signature", 14, finalY + 5);
        doc.text(`${user?.first_name} ${user?.last_name || "Manager Name"}`, 14, finalY + 10);
      }

      // Footer & Save
      const pageCount = (doc as any).internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: "right" });
      }

      doc.save(`${title.toLowerCase().replace(/\s+/g, '_')}_report.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Failed to generate PDF. Please try Excel export instead.");
    }
  };

  const exportToExcel = async (title: string, data: any[]) => {
    try {
      const workbook = new ExcelJS.Workbook();
      const worksheet = workbook.addWorksheet('JVD Report');

      // 1. Setup Columns (Improved Auto-fit estimation)
      const columns = Object.keys(data[0] || {}).map(key => {
        const headerLen = key.length;
        const maxContentLen = Math.max(...data.map(row => String(row[key] || '').length), 0);
        return {
          header: key.toUpperCase(),
          key: key,
          width: Math.max(headerLen, maxContentLen, 12) + 8 // More generous padding
        };
      });

      if (columns[0]) columns[0].width = Math.max(columns[0].width, 35);
      worksheet.columns = columns;

      // 2. Add Professional Header Section (Rows 1-6)
      worksheet.spliceRows(1, 0,
        ['JVD INTERNAL MANAGEMENT SYSTEM'],
        [`OFFICIAL REPORT: ${title.toUpperCase()}`],
        [`Generated by: ${user?.first_name} ${user?.last_name}`],
        [`Date: ${new Date().toLocaleString()}`],
        [`Reference: JVD-REF-${Math.floor(100000 + Math.random() * 900000)}`],
        [`Status: AUTHORIZED INTERNAL USE ONLY`],
        []
      );

      // Style the Header Section
      for (let i = 1; i <= 6; i++) {
        const row = worksheet.getRow(i);
        row.getCell(1).font = { bold: true, size: i === 1 ? 16 : 10, color: { argb: i === 1 ? 'FF1E3A8A' : 'FF64748B' } };
      }

      // 3. Add the Data Table (Starts at row 8)
      worksheet.getRow(8).values = Object.keys(data[0] || {}).map(k => k.toUpperCase());

      data.forEach((item) => {
        const cleanedItem = { ...item };
        Object.keys(cleanedItem).forEach(key => {
          if (typeof cleanedItem[key] === 'string') {
            cleanedItem[key] = cleanedItem[key].replace(/PHP /g, 'PHP ').replace(/₱/g, 'PHP ');
          }
        });
        worksheet.addRow(cleanedItem);
      });

      // 4. Style the Table Header (Row 8)
      const headerRow = worksheet.getRow(8);
      headerRow.eachCell((cell) => {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FF2563EB' }
        };
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
      });

      // 5. Style the Data Cells (Alignment Logic)
      worksheet.eachRow((row, rowNumber) => {
        if (rowNumber > 8 && rowNumber <= 8 + data.length) {
          row.eachCell((cell) => {
            cell.border = {
              top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
              left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
              bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
              right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
            };

            // Center-align numbers, percentages, and currencies
            const val = String(cell.value || '');
            const isNumeric = !isNaN(Number(cell.value)) || val.includes('%') || val.includes('PHP ');

            cell.alignment = {
              vertical: 'middle',
              horizontal: isNumeric ? 'center' : 'left',
              indent: isNumeric ? 0 : 1 // Slight indent for text
            };

            if (rowNumber % 2 === 0) {
              cell.fill = {
                type: 'pattern',
                pattern: 'solid',
                fgColor: { argb: 'FFF8FAFC' }
              };
            }
          });
        }
      });

      // 6. Add Signature Footer
      const footerStart = 8 + data.length + 3;
      worksheet.getRow(footerStart).values = ['--------------------------------------------------'];
      worksheet.getRow(footerStart + 1).values = ['Authorized Signature'];
      worksheet.getRow(footerStart + 2).values = [`${user?.first_name} ${user?.last_name}`];
      worksheet.getRow(footerStart + 3).values = ['JVD Events & Travel Management Co.'];

      for (let i = 0; i < 4; i++) {
        worksheet.getRow(footerStart + i).getCell(1).font = { size: 9, color: { argb: 'FF64748B' } };
      }

      // 7. Protection (Make headers non-editable)
      await worksheet.protect('jvd-secure', {
        selectLockedCells: true,
        selectUnlockedCells: true,
      });

      // 8. Generate and Save
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${title.toLowerCase().replace(/\s+/g, '_')}_report.xlsx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Excel Generation Error:", error);
      alert("Failed to generate Excel report.");
    }
  };

  if (isLoading) return <LoadingScreen />;


  if (error) {
    return (
      <div className="flex flex-col items-center justify-center h-full min-h-[400px] text-gray-500 gap-4">
        <p className="text-sm font-bold text-red-500 uppercase tracking-widest">Failed to load dashboard data</p>
        <button
          onClick={() => window.location.reload()}
          className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold uppercase tracking-wider hover:bg-blue-700 transition-all"
        >
          Retry
        </button>
      </div>
    );
  }

  const kpis = dashboardData?.kpis ?? {};
  const userDist = dashboardData?.user_distribution && dashboardData.user_distribution.length > 0
    ? dashboardData.user_distribution.map((d: any) => ({
      ...d,
      color: d.name === 'Drivers' ? '#3b82f6' :
        d.name === 'Agents' ? '#8b5cf6' :
          d.name === 'Accounting' ? '#10b981' :
            d.name === 'Procurement' ? '#f59e0b' :
              d.name === 'HR' ? '#ec4899' : '#6366f1'
    }))
    : [];

  // ── Live data — falls back to empty arrays so UI shows nothing rather than stale static data ──
  const localBookings = dashboardData?.local_bookings ?? [];
  const internationalBookings = dashboardData?.international_bookings ?? [];
  const pendingAndReservedBookings = dashboardData?.pending_reserved_bookings ?? [];
  const detailedCustomerData = dashboardData?.customer_list ?? [];
  const detailedEmployeeData = dashboardData?.employee_list ?? [];
  const detailedRevenueData = dashboardData?.revenue_export ?? [];


  const DownloadActions = ({ title, data, variant = 'dark' }: { title: string; data: any[]; variant?: 'dark' | 'light' }) => {
    const [isOpen, setIsOpen] = useState(false);
    const dropdownRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
      const handleClickOutside = (event: MouseEvent) => {
        if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
          setIsOpen(false);
        }
      };

      if (isOpen) {
        document.addEventListener('mousedown', handleClickOutside);
      }
      return () => {
        document.removeEventListener('mousedown', handleClickOutside);
      };
    }, [isOpen]);

    return (
      <div className="relative flex items-center" ref={dropdownRef}>
        <button
          onClick={(e) => { e.stopPropagation(); setIsOpen(!isOpen); }}
          className={`p-1.5 rounded-xl transition-all opacity-50 group-hover:opacity-100 ${variant === 'light'
            ? 'bg-white/20 hover:bg-white/30 text-white'
            : 'hover:bg-slate-50 dark:hover:bg-gray-800 text-gray-400 dark:text-gray-500 hover:text-blue-600 dark:hover:text-blue-400'
            }`}
        >
          <LuDownload className="w-3.5 h-3.5" />
        </button>

        {isOpen && (
          <div className="absolute top-full right-0 pt-2 z-[100]">
            <div className="w-32 bg-white dark:bg-gray-800 rounded-2xl shadow-2xl border border-gray-100 dark:border-gray-800 py-2">
              <button
                onClick={async (e) => { e.stopPropagation(); await exportToPDF(title, data); setIsOpen(false); }}
                className="w-full px-4 py-2 text-left text-[10px] font-bold text-gray-600 dark:text-gray-300 hover:bg-red-50 dark:hover:bg-red-500/10 hover:text-red-600 dark:hover:text-red-400 flex items-center gap-2 transition-colors"
              >
                <LuFileText className="w-3.5 h-3.5" />
                Export PDF
              </button>
              <button
                onClick={async (e) => { e.stopPropagation(); await exportToExcel(title, data); setIsOpen(false); }}
                className="w-full px-4 py-2 text-left text-[10px] font-bold text-gray-600 dark:text-gray-300 hover:bg-emerald-50 dark:hover:bg-emerald-500/10 hover:text-emerald-600 dark:hover:text-emerald-400 flex items-center gap-2 transition-colors"
              >
                <LuFileSpreadsheet className="w-3.5 h-3.5" />
                Export Excel
              </button>
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex flex-col gap-2 pb-4 lg:h-[calc(100vh-9.5rem)] lg:overflow-y-auto custom-scrollbar">

      {/* ── Top KPI Row ── */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 relative z-20 shrink-0">

        {/* KPI 1: Total Users */}
        <div className="relative rounded-2xl p-5 bg-gradient-to-br from-blue-500 to-blue-700 text-white shadow-lg shadow-blue-300/30 dark:shadow-blue-900/30 flex flex-col justify-between group hover:scale-[1.01] transition-all cursor-default min-h-[130px]">
          <div className="flex items-start justify-between">
            <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors">
              <LuUsers className="w-5 h-5 text-white" />
            </div>
            <div className="flex items-center gap-1">
              <DownloadActions variant="light" title="Global Personnel" data={detailedEmployeeData} />
            </div>
          </div>
          <div className="flex items-end justify-between mt-3">
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest opacity-70">Total Users</p>
              <p className="text-3xl font-black leading-none">{kpis.total_users ?? 0}</p>
            </div>
          </div>
        </div>

        {/* KPI 2: User Distribution */}
        <div className="relative rounded-2xl p-5 bg-gradient-to-br from-amber-400 to-orange-600 text-white shadow-lg shadow-amber-300/30 dark:shadow-amber-900/30 flex flex-col justify-between group hover:scale-[1.01] transition-all cursor-default min-h-[130px]">
          <div className="flex items-start justify-between">
            <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors">
              <LuUsers className="w-5 h-5 text-white" />
            </div>
            <DownloadActions variant="light" title="User Roles" data={userDist} />
          </div>
          <div className="flex items-end justify-between mt-3">
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest opacity-70">User Distribution</p>
              <p className="text-3xl font-black leading-none">
                {kpis.user_role_count ? `${kpis.user_role_count} Roles` : '0 Roles'}
              </p>
            </div>
          </div>
        </div>

        {/* KPI 3: Total Customers */}
        <div className="relative rounded-2xl p-5 bg-gradient-to-br from-violet-500 to-purple-700 text-white shadow-lg shadow-violet-300/30 dark:shadow-violet-900/30 flex flex-col justify-between group hover:scale-[1.01] transition-all cursor-default min-h-[130px]">
          <div className="flex items-start justify-between">
            <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors">
              <LuGlobe className="w-5 h-5 text-white" />
            </div>
            <div className="flex items-center gap-1">
              <DownloadActions variant="light" title="Customer Base" data={detailedCustomerData} />
            </div>
          </div>
          <div className="flex items-end justify-between mt-3">
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest opacity-70">Total Customers</p>
              <p className="text-3xl font-black leading-none">{(kpis.total_customers ?? 0).toLocaleString()}</p>
            </div>
          </div>
        </div>

        {/* KPI 4: Monthly Revenue */}
        <div className="relative rounded-2xl p-5 bg-gradient-to-br from-emerald-400 to-emerald-600 text-white shadow-lg shadow-emerald-300/30 dark:shadow-emerald-900/30 flex flex-col justify-between group hover:scale-[1.01] transition-all cursor-default min-h-[130px]">
          <div className="flex items-start justify-between">
            <div className="w-10 h-10 rounded-xl bg-white/20 backdrop-blur-sm flex items-center justify-center group-hover:bg-white/30 transition-colors">
              <LuBanknote className="w-5 h-5 text-white" />
            </div>
            <div className="flex items-center gap-2">
              <select className="bg-white/20 text-white text-[8px] font-black border-none rounded-lg px-1.5 py-0.5 outline-none cursor-pointer hover:bg-white/30 transition-colors uppercase tracking-wider">
                <option value="monthly" className="text-gray-800">Monthly</option>
                <option value="weekly" className="text-gray-800">Weekly</option>
                <option value="yearly" className="text-gray-800">Yearly</option>
              </select>
              <DownloadActions variant="light" title="Revenue Metrics" data={detailedRevenueData} />
            </div>
          </div>
          <div className="flex items-end justify-between mt-3">
            <div>
              <p className="text-[10px] font-black uppercase tracking-widest opacity-70">Monthly Revenue</p>
              <p className="text-3xl font-black leading-none">
                ₱{(kpis.monthly_revenue ?? 0) >= 1000000 ? `${((kpis.monthly_revenue ?? 0) / 1000000).toFixed(1)}M` : (kpis.monthly_revenue ?? 0).toLocaleString()}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ── Quick Approvals Action Panel for Admins ── */}
      {isApprover && pendingBudgets.length > 0 && (
        <div className="bg-white dark:bg-gray-900 border border-gray-100 dark:border-gray-800 rounded-[2rem] p-6 shadow-sm flex flex-col gap-4 animate-in fade-in slide-in-from-top-4 duration-500 shrink-0">
          <div className="flex items-center justify-between border-b border-gray-50 dark:border-gray-805 pb-3">
            <div>
              <h3 className="text-xs font-black text-gray-905 dark:text-white uppercase tracking-widest flex items-center gap-1.5">
                <span className="w-2 h-2 rounded-full bg-blue-500 animate-ping shrink-0" />
                Pending Cash Budget Approvals
              </h3>
              <p className="text-[9px] text-gray-400 font-bold uppercase tracking-wider mt-0.5">
                You have {pendingBudgets.length} pending cash budget request(s) requiring authorization.
              </p>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {pendingBudgets.map((budget: any) => {
              const preparerName = budget.prepared_by && typeof budget.prepared_by === 'object'
                ? `${budget.prepared_by.first_name || ''} ${budget.prepared_by.last_name || ''}`.trim()
                : 'Staff';
              return (
                <div
                  key={budget.id}
                  className="bg-gray-50/40 dark:bg-gray-800/40 border border-gray-100/70 dark:border-gray-800/70 rounded-2xl p-4 flex flex-col justify-between gap-3 hover:border-blue-200 dark:hover:border-blue-800 transition-all hover:scale-[1.01]"
                >
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-[8.5px] font-black text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-500/10 px-2 py-0.5 rounded-md uppercase">
                        {budget.trip_ticket?.control_no ?? `CB-${budget.id}`}
                      </span>
                      <span className="text-[10px] font-black text-gray-900 dark:text-white">
                        ₱{Number(budget.total_amount).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </span>
                    </div>
                    <h4 className="text-[10px] font-black text-gray-850 dark:text-gray-200 uppercase truncate">
                      {budget.destination || 'No Destination'}
                    </h4>
                    <p className="text-[8px] text-gray-400 font-bold mt-1 uppercase">
                      Prepared By: {preparerName}
                    </p>
                    {budget.plate_number && (
                      <p className="text-[7.5px] text-gray-400 font-medium mt-0.5">
                        Plate: {budget.plate_number}
                      </p>
                    )}
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <button
                      onClick={async () => {
                        try {
                          await cashBudgetApi.approve(budget.id);
                          toast.success('Cash budget request approved successfully!');
                          refetchCashBudgets();
                        } catch (err: any) {
                          toast.error('Approval failed: ' + (err.message || 'unknown error'));
                        }
                      }}
                      className="flex-1 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-[8px] font-black uppercase tracking-wider transition-all shadow-md shadow-emerald-600/10"
                    >
                      Approve
                    </button>
                    <button
                      onClick={async () => {
                        if (!confirm('Are you sure you want to decline this request?')) return;
                        try {
                          await cashBudgetApi.decline(budget.id);
                          toast.success('Cash budget request declined.');
                          refetchCashBudgets();
                        } catch (err: any) {
                          toast.error('Decline failed: ' + (err.message || 'unknown error'));
                        }
                      }}
                      className="py-1.5 px-3 bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-600 dark:text-gray-300 rounded-xl text-[8px] font-black uppercase tracking-wider transition-all"
                    >
                      Decline
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── 3-Column Analytics Grid ── */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-2 min-h-0 flex-1 relative z-10">

        {/* Column 1: Fleet Calendar */}
        <div className="h-full min-h-[500px] min-w-0">
          <CalendarFleetAvailability tickets={tickets} buses={buses} />
        </div>

        {/* Column 2: Heatmap + Travel Bookings */}
        <div className="flex flex-col gap-2 h-full min-h-0 min-w-0">

          {/* Local Travel Bookings List */}
          <div className="flex-[4] min-h-[250px] bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm p-2.5 flex flex-col animate-fadeIn">
            <div className="flex items-center justify-between pb-1.5 border-b border-gray-50 dark:border-gray-800 shrink-0">
              <div>
                <h3 className="text-[10px] font-black text-gray-900 dark:text-white uppercase tracking-widest flex items-center gap-1.5">
                  <LuGlobe className="w-3 h-3 text-emerald-500" />
                  Local Travel Bookings
                </h3>
              </div>
              <DownloadActions variant="dark" title="Local Bookings Report" data={localBookings} />
            </div>

            <div className="space-y-1 overflow-y-auto flex-1 mt-3 pr-0.5 custom-scrollbar">
              {localBookings.map((item, idx) => (
                <div key={item.id} className="flex items-center gap-2 bg-gray-50/50 dark:bg-gray-800/40 rounded-xl p-1.5 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 dark:bg-emerald-900/40 text-emerald-600 dark:text-emerald-400 flex items-center justify-center text-[9px] font-black shrink-0">
                    {idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1">
                      <span className="text-[7px] font-black text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-500/10 px-1.5 py-0.5 rounded">
                        {item.id}
                      </span>
                      <span className="text-[7px] text-gray-400 font-bold">{item.date}</span>
                    </div>
                    <h4 className="text-[9.5px] font-black text-gray-900 dark:text-white mt-0.5 truncate">
                      {item.customer} {'->'} <span className="text-emerald-600 dark:text-emerald-400">{item.destination}</span>
                    </h4>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-[9.5px] font-black text-gray-900 dark:text-white">{item.amount}</p>
                    <span className={`text-[6.5px] font-black uppercase px-1.5 py-0.5 rounded-full inline-block mt-0.5 ${item.status === 'Confirmed' ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' :
                      item.status === 'Pending' ? 'bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400' :
                        'bg-purple-50 dark:bg-purple-500/10 text-purple-600 dark:text-purple-400'
                      }`}>
                      {item.status}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Buses Under Maintenance List */}
          <div className="flex-[6] min-h-[250px] bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm p-2.5 flex flex-col">
            <div className="flex items-center justify-between pb-1.5 border-b border-gray-50 dark:border-gray-800 shrink-0">
              <h3 className="text-[10px] font-black text-gray-900 dark:text-white uppercase tracking-widest flex items-center gap-1.5">
                <LuBus className="w-3 h-3 text-amber-500" />
                Buses Under Maintenance
              </h3>
              <DownloadActions
                variant="dark"
                title="Buses Under Maintenance"
                data={busesUnderMaintenance.map((b: any) => ({
                  'Plate Number': b.plate_number,
                  'Model': b.model,
                  'Category': b.bus_category,
                  'Mileage': `${b.total_mileage?.toLocaleString() ?? 0} km`,
                  'Status': 'Under Maintenance'
                }))}
              />
            </div>

            <div className="space-y-1 overflow-y-auto flex-1 mt-3.5 pr-0.5 custom-scrollbar">
              {busesUnderMaintenance.slice(0, 6).map((item: any, idx: number) => (
                <div key={item.id} className="flex items-center gap-2 bg-gray-50/50 dark:bg-gray-800/40 rounded-xl p-1.5 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all">
                  <div className="w-5 h-5 rounded-full bg-amber-100 dark:bg-amber-900/40 text-amber-600 dark:text-amber-400 flex items-center justify-center text-[9px] font-black shrink-0">
                    {idx + 1}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1">
                      <span className="text-[7px] font-black text-amber-600 dark:text-amber-400 bg-amber-50 dark:bg-amber-500/10 px-1.5 py-0.5 rounded">
                        {item.plate_number}
                      </span>
                      <span className="text-[7px] text-gray-400 font-bold">{item.bus_category}</span>
                    </div>
                    <h4 className="text-[9.5px] font-black text-gray-900 dark:text-white mt-0.5 truncate">
                      {item.model}
                    </h4>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-[9.5px] font-black text-gray-900 dark:text-white">{item.total_mileage?.toLocaleString() ?? 0} km</p>
                    <span className="text-[6.5px] font-black uppercase px-1.5 py-0.5 rounded-full inline-block mt-0.5 bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400">
                      Maintenance
                    </span>
                  </div>
                </div>
              ))}
              {busesUnderMaintenance.length === 0 && (
                <div className="flex flex-col items-center justify-center flex-1 h-full py-10 text-gray-400 dark:text-gray-500">
                  <LuBus className="w-8 h-8 mb-2 opacity-50 text-gray-300 animate-pulse" />
                  <p className="text-[10px] font-black uppercase tracking-wider">No Buses Under Maintenance</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Column 3: Performers + Charts */}
        <div className="flex flex-col gap-2 h-full min-h-0 min-w-0">

          {/* Top Performers / Travel */}
          <div className="flex-[4.5] min-h-[250px] bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm p-2.5 flex flex-col">
            <div className="flex items-center justify-between pb-1 border-b border-gray-50 dark:border-gray-800 shrink-0">
              <h3 className="text-[10px] font-black text-gray-900 dark:text-white uppercase tracking-widest flex items-center gap-1.5">
                <LuGlobe className="w-3 h-3 text-rose-500" />
                International Travel booking
              </h3>
            </div>

            <div className="flex-1 overflow-y-auto space-y-1.5 mt-3.5 pr-0.5 custom-scrollbar">
              {/* International Travel Bookings */}
              <div>
                <h4 className="text-[8px] font-black text-rose-500 uppercase tracking-wider mb-1">International Travel Bookings</h4>
                <div className="space-y-0.5">
                  {internationalBookings.map((item, idx) => (
                    <div key={item.id} className="flex items-center gap-1.5 bg-gray-50/50 dark:bg-gray-800/40 rounded-xl p-1 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all">
                      <div className="w-4 h-4 rounded-full bg-rose-105 dark:bg-rose-950/40 text-rose-600 dark:text-rose-450 flex items-center justify-center text-[8px] font-black shrink-0">
                        {idx + 1}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1">
                          <span className="text-[6.5px] font-black text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-500/10 px-1 py-0.2 rounded">
                            {item.id}
                          </span>
                          <span className="text-[6.5px] text-gray-400 font-bold">{item.date}</span>
                        </div>
                        <h4 className="text-[9px] font-black text-gray-950 dark:text-white truncate mt-0.5">
                          {item.customer} {'->'} <span className="text-rose-600 dark:text-rose-400">{item.destination}</span>
                        </h4>
                      </div>
                      <div className="text-right shrink-0 pr-0.5">
                        <p className="text-[8.5px] font-black text-rose-600 dark:text-rose-400 leading-none">{item.amount}</p>
                        <span className={`text-[6px] font-black uppercase px-1 py-0.2 rounded-full inline-block mt-0.5 ${item.status === 'Confirmed' ? 'bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400' :
                          item.status === 'Pending' ? 'bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400' :
                            'bg-purple-50 dark:bg-purple-500/10 text-purple-600 dark:text-purple-400'
                          }`}>
                          {item.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>


            </div>
          </div>

          {/* Pending & Reserved widget */}
          <div className="flex-[5.5] min-h-0 bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm p-2.5 flex flex-col">
            <div className="flex items-center justify-between pb-1 border-b border-gray-50 dark:border-gray-800 shrink-0">
              <div className="flex items-center gap-3">
                <span className="text-[10px] font-black uppercase tracking-widest flex items-center gap-1.5 text-blue-600 dark:text-white">
                  <LuTicket className="w-3 h-3 text-blue-500" />
                  Pending & Reserved
                </span>
              </div>
              <div className="flex items-center gap-1.5">
                <DownloadActions variant="dark" title="Pending and Reserved Bookings" data={pendingAndReservedBookings} />
              </div>
            </div>

            <div className="flex-1 min-h-0 mt-3 overflow-y-auto custom-scrollbar">
                <div className="space-y-1 pr-0.5">
                  {pendingAndReservedBookings.map((item, idx) => (
                    <div key={item.id} className="flex items-center gap-2 bg-gray-50/50 dark:bg-gray-800/40 rounded-xl p-1.5 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-800 transition-all animate-fadeIn">
                      <div className="w-5 h-5 rounded-full bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400 flex items-center justify-center text-[9px] font-black shrink-0">
                        {idx + 1}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1">
                          <span className="text-[7px] font-black text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-500/10 px-1.5 py-0.5 rounded">
                            {item.id}
                          </span>
                          <span className="text-[7px] text-gray-400 font-bold">{item.date}</span>
                          <span className="text-[6.5px] font-black text-gray-500 dark:text-gray-400 bg-gray-100 dark:bg-gray-800 px-1 py-0.2 rounded uppercase">
                            {item.type}
                          </span>
                        </div>
                        <h4 className="text-[9.5px] font-black text-gray-900 dark:text-white mt-0.5 truncate">
                          {item.customer} {'->'} <span className="text-blue-600 dark:text-blue-400">{item.destination}</span>
                        </h4>
                      </div>
                      <div className="text-right shrink-0">
                        <p className="text-[9.5px] font-black text-gray-900 dark:text-white">{item.amount}</p>
                        <span className={`text-[6.5px] font-black uppercase px-1.5 py-0.5 rounded-full inline-block mt-0.5 ${item.status === 'Pending' ? 'bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400' :
                          'bg-purple-50 dark:bg-purple-500/10 text-purple-600 dark:text-purple-400'
                          }`}>
                          {item.status}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

// ── Fleet Schedule Data ───────────────────────────────────────────────────────
const today = new Date();
const y = today.getFullYear();
const m = today.getMonth();

function isSameDay(a: Date, b: Date) {
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}

function CalendarFleetAvailability({ tickets = [], buses = [] }: { tickets?: any[]; buses?: any[] }) {
  const [calDate, setCalDate] = useState(new Date(y, m, 1));
  const [selected, setSelected] = useState<Date>(today);

  const calYear = calDate.getFullYear();
  const calMonth = calDate.getMonth();

  const daysInMonth = new Date(calYear, calMonth + 1, 0).getDate();
  const firstWeekday = new Date(calYear, calMonth, 1).getDay();

  const cells = useMemo(() => {
    const arr: (Date | null)[] = Array(firstWeekday).fill(null);
    for (let d = 1; d <= daysInMonth; d++) arr.push(new Date(calYear, calMonth, d));
    return arr;
  }, [calYear, calMonth, daysInMonth, firstWeekday]);

  // Build live schedules from trip tickets
  const fleetSchedules = useMemo(() => {
    return tickets.map((t: any) => ({
      id: t.id,
      date: t.date_of_travel ? new Date(t.date_of_travel) : new Date(),
      bus: t.bus?.plate_number || t.plate_no || 'N/A',
      busModel: t.bus?.model || '',
      plate: t.bus?.plate_number || t.plate_no || 'N/A',
      route: `${t.pick_up || 'N/A'} - ${t.drop_off || 'N/A'}`,
      driver: t.driver ? `${t.driver.first_name || ''} ${t.driver.last_name || ''}`.trim() : (t.driver?.name || 'N/A'),
      depart: '09:00 AM',
      status: t.status === 'completed' ? 'completed' : t.status === 'approved' ? 'in_service' : 'scheduled',
      seats: t.no_of_passengers || 45,
    }));
  }, [tickets]);

  const selectedEvents = useMemo(() => {
    return fleetSchedules.filter(s => isSameDay(s.date, selected));
  }, [fleetSchedules, selected]);

  const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const DAY_LABELS = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];

  const occupiedToday = useMemo(() => {
    return Array.from(new Set(selectedEvents.map(d => d.bus)));
  }, [selectedEvents]);

  const availableToday = useMemo(() => {
    if (!buses || buses.length === 0) {
      const allBusesPlaceholder = [
        { id: 1, plate_number: 'XYZ-001', model: 'BUS-001', seating_capacity: 45 },
        { id: 2, plate_number: 'XYZ-002', model: 'BUS-002', seating_capacity: 55 },
        { id: 3, plate_number: 'XYZ-003', model: 'BUS-003', seating_capacity: 40 },
        { id: 4, plate_number: 'XYZ-004', model: 'BUS-004', seating_capacity: 50 },
        { id: 5, plate_number: 'XYZ-005', model: 'BUS-005', seating_capacity: 60 },
        { id: 6, plate_number: 'XYZ-006', model: 'BUS-006', seating_capacity: 45 },
        { id: 7, plate_number: 'XYZ-007', model: 'BUS-007', seating_capacity: 50 },
      ];
      return allBusesPlaceholder.filter((b: any) => !occupiedToday.includes(b.model));
    }
    return buses.filter((b: any) => !occupiedToday.includes(b.plate_number));
  }, [buses, occupiedToday]);

  return (
    <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] border border-gray-100/50 dark:border-gray-800 shadow-sm p-3 flex flex-col h-full min-h-0">
      {/* Title Header */}
      <div className="flex items-center justify-between pb-2 border-b border-gray-50 dark:border-gray-850 shrink-0">
        <div>
          <h3 className="text-xs font-black text-gray-900 dark:text-white uppercase tracking-widest flex items-center gap-1.5">
            <LuBus className="w-3.5 h-3.5 text-blue-500" />
            Fleet Calendar & Availability
          </h3>
          <p className="text-[9px] text-gray-400 font-bold uppercase tracking-wider">Select date to track status</p>
        </div>
      </div>

      {/* Calendar Area */}
      <div className="flex flex-col gap-1.5 mt-3.5 shrink-0">
        {/* Navigation */}
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-black text-gray-850 dark:text-white uppercase tracking-wider">
            {MONTH_NAMES[calMonth]} {calYear}
          </span>
          <div className="flex items-center gap-1">
            <button
              onClick={() => setCalDate(new Date(calYear, calMonth - 1, 1))}
              className="w-5 h-5 rounded-lg flex items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors text-gray-500"
            >
              <LuChevronLeft className="w-3 h-3" />
            </button>
            <button
              onClick={() => setCalDate(new Date(calYear, calMonth + 1, 1))}
              className="w-5 h-5 rounded-lg flex items-center justify-center hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors text-gray-500"
            >
              <LuChevronRight className="w-3 h-3" />
            </button>
          </div>
        </div>

        {/* Weekdays */}
        <div className="grid grid-cols-7 text-center">
          {DAY_LABELS.map((d, i) => (
            <div key={i} className="text-[8px] font-black text-gray-400 dark:text-gray-600 py-0.5 uppercase">{d}</div>
          ))}
        </div>

        {/* Days Grid */}
        <div className="grid grid-cols-7 gap-0.5">
          {cells.map((date, i) => {
            if (!date) return <div key={`empty-${i}`} className="h-6.5" />;
            const events = fleetSchedules.filter(s => isSameDay(s.date, date));
            const isToday = isSameDay(date, today);
            const isSel = isSameDay(date, selected);
            return (
              <button
                key={date.toISOString()}
                onClick={() => setSelected(date)}
                className={`relative flex flex-col items-center justify-center rounded-lg transition-all h-6.5 text-[9px] font-black ${isSel
                  ? 'bg-blue-500 text-white shadow-md shadow-blue-200/50 dark:shadow-blue-900/30'
                  : isToday
                    ? 'bg-blue-50 dark:bg-blue-500/10 text-blue-600 dark:text-blue-400 ring-1 ring-blue-200 dark:ring-blue-500/30'
                    : 'hover:bg-gray-50 dark:hover:bg-gray-800 text-gray-700 dark:text-gray-300'
                  }`}
              >
                <span>{date.getDate()}</span>
                {events.length > 0 && (
                  <span className={`w-1 h-1 rounded-full mt-0.5 ${isSel ? 'bg-white' : 'bg-blue-500'}`} />
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Dynamic Available / Occupied Row split */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2 pt-2 border-t border-gray-50 dark:border-gray-800/80 min-h-0 flex-1">
        {/* Left: Available */}
        <div className="flex flex-col min-h-0">
          <div className="flex items-center justify-between bg-emerald-50 dark:bg-emerald-500/10 px-2 py-1 rounded-xl mb-1.5 shrink-0">
            <span className="text-[9px] font-black text-emerald-600 dark:text-emerald-400 uppercase tracking-wider">Avail</span>
            <span className="text-[9px] font-black text-emerald-600 dark:text-emerald-400">{availableToday.length}</span>
          </div>
          <div className="space-y-1 overflow-y-auto pr-1 flex-1">
            {availableToday.map((b: any) => (
              <div key={b.id} className="flex items-center justify-between p-1.5 rounded-lg bg-gray-50/40 dark:bg-gray-800/40 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-855 transition-all shadow-sm">
                <div className="flex items-center gap-1 min-w-0 flex-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0" />
                  <span className="text-[8.5px] font-black text-gray-900 dark:text-white uppercase tracking-wider shrink-0">{b.model || b.plate_number}</span>
                  <span className="text-[7.5px] text-gray-400 dark:text-gray-500 font-bold truncate">({b.plate_number})</span>
                </div>
                <span className="text-[8.5px] font-black text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-500/10 px-1 py-0.5 rounded shrink-0">{b.seating_capacity || 49} Seats</span>
              </div>
            ))}
          </div>
        </div>

        {/* Right: Occupied */}
        <div className="flex flex-col min-h-0">
          <div className="flex items-center justify-between bg-amber-50 dark:bg-amber-500/10 px-2 py-1 rounded-xl mb-1.5 shrink-0">
            <span className="text-[9px] font-black text-amber-600 dark:text-amber-400 uppercase tracking-wider">Occupied</span>
            <span className="text-[9px] font-black text-amber-600 dark:text-amber-400">{occupiedToday.length}</span>
          </div>
          <div className="space-y-1 overflow-y-auto pr-1 flex-1">
            {occupiedToday.length === 0 ? (
              <p className="text-[9px] text-gray-400 dark:text-gray-500 italic p-1.5">No occupied buses.</p>
            ) : (
              occupiedToday.map((b, idx) => {
                const dispatch = selectedEvents.find(s => s.bus === b);
                const plate = dispatch?.plate || 'XYZ 7890';
                const driver = dispatch?.driver || 'Standby Driver';
                const route = dispatch?.route || 'In route';
                const depart = dispatch?.depart || 'N/A';
                return (
                  <div key={`${b}-${idx}`} className="flex flex-col gap-0.5 p-1.5 rounded-lg bg-gray-50/40 dark:bg-gray-800/40 border border-gray-100/50 dark:border-gray-800/50 hover:bg-gray-50 dark:hover:bg-gray-855 transition-all shadow-sm">
                    <div className="flex items-center justify-between gap-1">
                      <div className="flex items-center gap-1 min-w-0 flex-1">
                        <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0 animate-pulse" />
                        <span className="text-[8.5px] font-black text-gray-900 dark:text-white uppercase tracking-wider shrink-0">{dispatch?.busModel || b}</span>
                        <span className="text-[7.5px] text-gray-400 dark:text-gray-500 font-bold truncate">({plate})</span>
                      </div>
                      <span className="text-[7.5px] text-amber-600 dark:text-amber-400 font-black uppercase tracking-wider bg-amber-50 dark:bg-amber-500/10 px-1 py-0.5 rounded shrink-0">Dep {depart}</span>
                    </div>
                    <div className="flex items-center justify-between text-[7.5px] font-bold text-gray-500 dark:text-gray-400 pl-2.5">
                      <span className="truncate max-w-[65%]">{route}</span>
                      <span className="truncate max-w-[35%] opacity-75 text-right">{driver}</span>
                    </div>

                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

