<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Charter Booking Confirmation</title><style>
@page{size:A4;margin:13mm 15mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px;line-height:1.45;margin:0}.header,.meta,.summary{width:100%;border-collapse:collapse}.header{border-bottom:3px solid #173b68;padding-bottom:9px}.brand{font-size:15px;font-weight:bold;color:#173b68}.title{text-align:right;font-size:15px;font-weight:bold;letter-spacing:1px}.muted{color:#627086}.meta{margin:13px 0}.meta td{width:50%;padding:7px 9px;border:1px solid #d9e3ef;background:#f6f9fc;vertical-align:top}.label{display:block;font-size:7px;font-weight:bold;letter-spacing:.5px;text-transform:uppercase;color:#617289;margin-bottom:2px}.section{font-size:9px;font-weight:bold;color:#173b68;text-transform:uppercase;letter-spacing:.7px;margin:15px 0 6px;border-bottom:1px solid #b7c9dd;padding-bottom:4px}.route{padding:10px;border:1px solid #d9e3ef;background:#fbfdff;font-size:10px;font-weight:bold}.summary td{padding:6px 0}.summary .amount{text-align:right;font-weight:bold}.notice{margin-top:14px;padding:9px 11px;border-left:3px solid #d28a18;background:#fff9ed;color:#5d471d}.footer{margin-top:24px;padding-top:7px;border-top:1px solid #cbd6e1;color:#627086;font-size:7px}.signatures{width:100%;border-collapse:collapse;margin-top:34px}.signatures td{width:33%;text-align:center;padding:0 10px}.line{border-top:1px solid #39495d;padding-top:4px}
</style></head><body>
<table class="header"><tr><td><div class="brand">{{ $company['name'] }}</div><div class="muted">{{ $company['address'] }}<br>{{ $company['phone'] }} | {{ $company['email'] }}</div></td><td class="title">CHARTER BOOKING<br>CONFIRMATION<br><span class="muted" style="font-size:8px">{{ $booking->reference }}</span></td></tr></table>
<table class="meta"><tr><td><span class="label">Client</span><strong>{{ $booking->lead_name }}</strong><br>{{ $booking->lead_contact }}<br>{{ $booking->lead_email }}</td><td><span class="label">Booking status</span><strong>{{ strtoupper($booking->status) }}</strong><br><span class="label" style="margin-top:5px">Invoice</span>{{ $booking->invoice?->invoice_number ?? 'Pending' }}</td></tr><tr><td><span class="label">Service</span>{{ $booking->ratePlan?->service?->name ?? $booking->ratePlan?->name }}</td><td><span class="label">Passengers</span>{{ $booking->passenger_count }} passenger(s)</td></tr></table>
<div class="section">Confirmed schedule</div><table class="meta"><tr><td><span class="label">Pickup date and time</span>{{ $booking->starts_at->format('D, M d Y h:i A') }}<br>{{ $booking->pickup_location }}</td><td><span class="label">Return / end time</span>{{ $booking->ends_at->format('D, M d Y h:i A') }}<br>{{ $booking->destination }}</td></tr></table>
<div class="section">Route</div><div class="route">{{ $booking->pickup_location }} &nbsp; to &nbsp; {{ $booking->destination }}@if(count($booking->stops ?? []))<br><span class="muted" style="font-size:8px;font-weight:normal">Stops: {{ implode(' | ', $booking->stops) }}</span>@endif</div>
<div class="section">Transport assignment</div><table class="meta"><tr><td><span class="label">Vehicle</span>{{ $booking->bus?->plate_number ?? 'To be assigned' }} {{ $booking->bus ? '- '.$booking->bus->model : '' }}</td><td><span class="label">Driver</span>{{ $booking->driver ? trim($booking->driver->first_name.' '.$booking->driver->last_name) : 'To be assigned' }}@if($booking->driver)<br><span class="muted">{{ $booking->driver->phone ?: 'Phone not recorded' }} | {{ $booking->driver->email ?: 'Email not recorded' }}</span>@endif</td></tr></table>
<div class="section">Commercial summary</div><table class="summary"><tr><td>Service subtotal</td><td class="amount">PHP {{ number_format($booking->invoice?->subtotal ?? $booking->subtotal,2) }}</td></tr><tr><td>VAT</td><td class="amount">PHP {{ number_format($booking->invoice?->tax_amount ?? 0,2) }}</td></tr><tr><td><strong>Total booking value</strong></td><td class="amount"><strong>PHP {{ number_format($booking->invoice?->total_amount ?? 0,2) }}</strong></td></tr><tr><td>Balance due</td><td class="amount">PHP {{ number_format($booking->invoice?->balance ?? 0,2) }}</td></tr></table>
<div class="notice"><strong>Operations note:</strong> This confirmation reserves the stated vehicle and driver schedule. Any scope, route, timing, or passenger-count change must be approved and reissued before dispatch.</div>
<table class="signatures"><tr><td><div class="line">Prepared by</div></td><td><div class="line">Client acknowledgement</div></td><td><div class="line">Operations approval</div></td></tr></table><div class="footer">Internal booking confirmation | Generated {{ $generatedAt->format('M d, Y h:i A') }} | {{ $company['name'] }}</div></body></html>
