<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Charter Dispatch Sheet</title><style>
@page{size:A4;margin:12mm 14mm 22mm}*{box-sizing:border-box}body{font-family:DejaVu Sans,sans-serif;color:#142033;font-size:9px;margin:0;line-height:1.4}.header,.grid,.signatures{width:100%;border-collapse:collapse}.header{border-bottom:3px solid #123c69;padding-bottom:8px}.brand{font-size:15px;font-weight:bold;color:#123c69}.title{text-align:right;font-size:15px;font-weight:bold;letter-spacing:1px}.grid{margin:12px 0}.grid td{width:50%;padding:7px 9px;border:1px solid #dbe5ef;vertical-align:top}.label{display:block;font-size:7px;font-weight:bold;text-transform:uppercase;letter-spacing:.5px;color:#607087;margin-bottom:2px}.section{margin-top:13px;background:#174a8b;color:#fff;padding:5px 7px;font-size:8px;font-weight:bold;text-transform:uppercase;letter-spacing:.6px}.route{padding:10px;border:1px solid #dbe5ef;background:#f6f9fc;font-size:10px;font-weight:bold}.checklist{width:100%;border-collapse:collapse}.checklist td{padding:6px;border:1px solid #dbe5ef}.box{display:inline-block;width:10px;height:10px;border:1px solid #53657a;margin-right:5px;vertical-align:-1px}.signatures{margin-top:30px}.signatures td{width:33%;padding:0 12px;text-align:center}.line{border-top:1px solid #39495d;padding-top:4px}.footer{display:none}body>.header{display:none}@include('pdf.partials.brand-styles')</style></head><body>
@include('pdf.partials.brand-header', ['documentTitle' => 'Operations Dispatch Sheet', 'documentReference' => $booking->reference, 'documentDate' => $booking->starts_at])
@include('pdf.partials.brand-footer', ['footerNote' => 'Confidential internal dispatch document. Complete all checks and approvals before vehicle release.'])
<table class="header"><tr><td><div class="brand">{{ $company['name'] }}</div><div>{{ $company['phone'] }} | {{ $company['email'] }}</div></td><td class="title">OPERATIONS<br>DISPATCH SHEET<br><span style="font-size:8px;color:#607087">{{ $booking->reference }}</span></td></tr></table>
<table class="grid"><tr><td><span class="label">Dispatch schedule</span><strong>{{ $booking->starts_at->format('D, M d Y h:i A') }}</strong> to {{ $booking->ends_at->format('D, M d Y h:i A') }}</td><td><span class="label">Passenger count</span><strong>{{ $booking->passenger_count }} passenger(s)</strong></td></tr><tr><td colspan="2"><span class="label">Client / on-site contact</span>{{ $booking->lead_name }} | {{ $booking->lead_contact }} | {{ $booking->lead_email }}</td></tr></table>
@php
    $fleet = $booking->fleet_assignments ?: [[
        'plate_number' => $booking->bus?->plate_number,
        'model' => $booking->bus?->model,
        'seating_capacity' => $booking->bus?->seating_capacity,
        'driver_name' => $booking->driver ? trim($booking->driver->first_name.' '.$booking->driver->last_name) : null,
        'driver_phone' => $booking->driver?->phone,
    ]];
@endphp
<div class="section">Fleet dispatch ({{ count($fleet) }} unit{{ count($fleet) === 1 ? '' : 's' }})</div>
<table class="jvd-data-table"><thead><tr><th>Unit</th><th>Vehicle / plate</th><th>Capacity</th><th>Assigned driver</th><th>Contact</th></tr></thead><tbody>@foreach($fleet as $index => $assignment)<tr><td>{{ $index + 1 }}</td><td><strong>{{ $assignment['plate_number'] ?? 'UNASSIGNED' }}</strong><br>{{ $assignment['model'] ?? '' }}</td><td>{{ $assignment['seating_capacity'] ?? '-' }}</td><td>{{ $assignment['driver_name'] ?? 'UNASSIGNED' }}</td><td>{{ $assignment['driver_phone'] ?? 'Not recorded' }}</td></tr>@endforeach</tbody></table>
<div class="section">Route and stops</div><div class="route">Pickup: {{ $booking->pickup_location }}<br>Destination: {{ $booking->destination }}@if(count($booking->stops ?? []))<br>Stops: {{ implode(' | ', $booking->stops) }}@endif</div>
<div class="section">Dispatch instructions</div><table class="checklist"><tr><td><span class="box"></span>Vehicle condition and fuel check completed</td><td><span class="box"></span>Driver briefing and route confirmation completed</td></tr><tr><td><span class="box"></span>Client contact and pickup time reconfirmed</td><td><span class="box"></span>Passenger count and special requirements verified</td></tr><tr><td colspan="2"><span class="label">Operations notes</span>{{ $booking->operations_notes ?: 'None recorded.' }}</td></tr></table>
<table class="signatures"><tr><td><div class="line">Dispatcher</div></td><td><div class="line">Driver acknowledgement</div></td><td><div class="line">Operations manager</div></td></tr></table><div class="footer">Confidential internal operations document | Generated {{ $generatedAt->format('M d, Y h:i A') }}</div></body></html>
