<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * ER: WORK_ORDER entity — JVD_System_Architecture.pdf § 6.1
     * Flow: Open → In Progress → Completed
     * Can be auto-generated by PMS (See § 5.3 and § 5.5)
     */
    public function up(): void
    {
        Schema::create('work_orders', function (Blueprint $table) {
            $table->id();
            $table->string('wo_number')->unique();
            $table->foreignId('bus_id')->constrained('buses')->restrictOnDelete();
            $table->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('created_by')->constrained('users')->restrictOnDelete();
            $table->enum('status', ['open', 'in_progress', 'completed'])->default('open');
            $table->enum('priority', ['routine', 'urgent', 'critical'])->default('routine');
            $table->text('description');
            $table->text('parts_used')->nullable();
            $table->decimal('cost', 10, 2)->default(0);
            $table->boolean('auto_generated')->default(false);  // True when created by PMS
            $table->timestamps();
            $table->softDeletes();

            $table->index('status');
            $table->index('priority');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('work_orders');
    }
};
