import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { useNavigate } from 'react-router-dom';
import {
  LuUsers,
  LuDollarSign,
  LuShoppingCart,
  LuPackage,
  LuGlobe,
  LuArrowUpRight,
  LuActivity,
  LuCircle,
  LuFileText,
  LuClipboardList,
  LuBus,
  LuCircleUser,
  LuReceipt,
  LuDownload,
  LuFileSpreadsheet,
} from 'react-icons/lu';
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  LineChart,
  Line,
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';

// Mock data for different branches
const branchData = {
  accounting: [
    { name: 'Mon', value: 4000 },
    { name: 'Tue', value: 3000 },
    { name: 'Wed', value: 5000 },
    { name: 'Thu', value: 2780 },
    { name: 'Fri', value: 1890 },
    { name: 'Sat', value: 2390 },
    { name: 'Sun', value: 3490 },
  ],
  procurement: [
    { name: 'Mon', value: 12 },
    { name: 'Tue', value: 19 },
    { name: 'Wed', value: 15 },
    { name: 'Thu', value: 22 },
    { name: 'Fri', value: 30 },
    { name: 'Sat', value: 10 },
    { name: 'Sun', value: 18 },
  ],
  inventory: [
    { name: 'Mon', value: 85 },
    { name: 'Tue', value: 88 },
    { name: 'Wed', value: 82 },
    { name: 'Thu', value: 90 },
    { name: 'Fri', value: 95 },
    { name: 'Sat', value: 80 },
    { name: 'Sun', value: 85 },
  ],
  travel: [
    { name: 'Mon', value: 5 },
    { name: 'Tue', value: 8 },
    { name: 'Wed', value: 12 },
    { name: 'Thu', value: 7 },
    { name: 'Fri', value: 15 },
    { name: 'Sat', value: 20 },
    { name: 'Sun', value: 12 },
  ],
};

const mainChartData = {
  Day: [
    { name: '8 AM', revenue: 100000 },
    { name: '10 AM', revenue: 300000 },
    { name: '12 PM', revenue: 500000 },
    { name: '2 PM', revenue: 400000 },
    { name: '4 PM', revenue: 800000 },
    { name: '6 PM', revenue: 600000 },
  ],
  Week: [
    { name: 'Mon', revenue: 1200000 },
    { name: 'Tue', revenue: 1500000 },
    { name: 'Wed', revenue: 1100000 },
    { name: 'Thu', revenue: 1800000 },
    { name: 'Fri', revenue: 2100000 },
    { name: 'Sat', revenue: 2300000 },
    { name: 'Sun', revenue: 1900000 },
  ],
  Month: [
    { name: '1st', revenue: 1200000 },
    { name: '5th', revenue: 1500000 },
    { name: '10th', revenue: 1300000 },
    { name: '15th', revenue: 1800000 },
    { name: '20th', revenue: 2100000 },
    { name: '25th', revenue: 2300000 },
    { name: '30th', revenue: 2400000 },
  ],
  Year: [
    { name: 'January', revenue: 1050000 },
    { name: 'February', revenue: 1280000 },
    { name: 'March', revenue: 1520000 },
    { name: 'April', revenue: 1850000 },
    { name: 'May', revenue: 2210000 },
    { name: 'June', revenue: 2400000 },
    { name: 'July', revenue: 2100000 },
    { name: 'August', revenue: 2300000 },
    { name: 'September', revenue: 2500000 },
    { name: 'October', revenue: 2700000 },
    { name: 'November', revenue: 2900000 },
    { name: 'December', revenue: 3200000 },
  ],
};

export default function Dashboard() {
  const { user } = useAuth();
  const { theme } = useTheme();
  const navigate = useNavigate();

  const [activeFilter, setActiveFilter] = useState<keyof typeof mainChartData>('Month');

  const exportToPDF = (title: string, data: any[]) => {
    try {
      const doc = new jsPDF();

      // Add Logo
      try {
        doc.addImage('/JVDlogo-removebg-preview.png', 'PNG', 160, 10, 35, 35);
      } catch (e) {
        console.warn("Logo failed to load, skipping...", e);
      }

      // Header Section
      doc.setFontSize(22);
      doc.setTextColor(30, 64, 175);
      doc.setFont("helvetica", "bold");
      doc.text("JVD MANAGEMENT SYSTEM", 14, 25);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.setFont("helvetica", "normal");
      doc.text("INTERNAL ORGANIZATIONAL REPORT", 14, 32);

      // Company Address (Mock)
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("UNIT 6 -Aryanna Village Center Brgy 175. Susano Road Camarin, Caloocan City, Caloocan, Philippines", 14, 37);
      doc.text("Contact: +63 976 - 4711 - 294", 14, 41);
      doc.text("Tel: 02 - 82938068", 14, 45);

      doc.setDrawColor(226, 232, 240);
      doc.line(14, 47, 196, 47);

      // Report Title & Meta
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.setFont("helvetica", "bold");
      doc.text(`Official Report: ${title}`, 14, 55);

      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated by: ${user?.first_name} ${user?.last_name || 'Authorized Personnel'}`, 14, 62);
      doc.text(`Date: ${new Date().toLocaleString()}`, 14, 67);
      doc.text(`Reference ID: JVD-REF-${Math.floor(100000 + Math.random() * 900000)}`, 14, 72);



      // Main Data Table
      autoTable(doc, {
        head: [Object.keys(data[0]).map(k => k.toUpperCase())],
        body: data.map(obj => Object.values(obj)),
        startY: 80,
        theme: 'grid',
        headStyles: {
          fillColor: [37, 99, 235],
          textColor: 255,
          fontStyle: 'bold',
          fontSize: 10,
          cellPadding: 4
        },
        bodyStyles: {
          fontSize: 9,
          cellPadding: 3,
          fillColor: false // Transparent to show watermark behind
        },
        alternateRowStyles: {
          fillColor: false // Transparent to show watermark behind
        },
        margin: { top: 80 }
      });

      // Signature Section
      let finalY = 240; // Default fallback position
      try {
        if ((doc as any).lastAutoTable && (doc as any).lastAutoTable.finalY) {
          finalY = (doc as any).lastAutoTable.finalY + 20;
        }
      } catch (e) {
        console.warn("Could not determine table end, using default Y");
      }

      if (finalY < 270) {
        doc.setDrawColor(200);
        doc.line(14, finalY, 70, finalY);
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text("Authorized Signature", 14, finalY + 5);
        doc.text(`${user?.first_name} ${user?.last_name || "Manager Name"}`, 14, finalY + 10);
      }

      // Footer & Save
      const pageCount = (doc as any).internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: "right" });
      }

      doc.save(`${title.toLowerCase().replace(/\s+/g, '_')}_report.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Failed to generate PDF. Please try Excel export instead.");
    }
  };

  const exportToExcel = async (title: string, data: any[]) => {
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('JVD Report');

    // 1. Setup Columns (Improved Auto-fit estimation)
    const columns = Object.keys(data[0] || {}).map(key => {
      const headerLen = key.length;
      const maxContentLen = Math.max(...data.map(row => String(row[key] || '').length), 0);
      return {
        header: key.toUpperCase(),
        key: key,
        width: Math.max(headerLen, maxContentLen, 12) + 8 // More generous padding
      };
    });

    if (columns[0]) columns[0].width = Math.max(columns[0].width, 35);
    worksheet.columns = columns;

    // 2. Add Professional Header Section (Rows 1-6)
    worksheet.insertRow(1, ['JVD INTERNAL MANAGEMENT SYSTEM']);
    worksheet.insertRow(2, [`OFFICIAL REPORT: ${title.toUpperCase()}`]);
    worksheet.insertRow(3, [`Generated by: ${user?.first_name} ${user?.last_name}`]);
    worksheet.insertRow(4, [`Date: ${new Date().toLocaleString()}`]);
    worksheet.insertRow(5, [`Reference: JVD-REF-${Math.floor(100000 + Math.random() * 900000)}`]);
    worksheet.insertRow(6, [`Status: AUTHORIZED INTERNAL USE ONLY`]);
    worksheet.insertRow(7, []); // Spacer

    // Style the Header Section
    for (let i = 1; i <= 6; i++) {
      const row = worksheet.getRow(i);
      row.getCell(1).font = { bold: true, size: i === 1 ? 16 : 10, color: { argb: i === 1 ? 'FF1E3A8A' : 'FF64748B' } };
    }

    // 3. Add the Data Table (Starts at row 8)
    worksheet.getRow(8).values = Object.keys(data[0] || {}).map(k => k.toUpperCase());

    data.forEach((item) => {
      worksheet.addRow(item);
    });

    // 4. Style the Table Header (Row 8)
    const headerRow = worksheet.getRow(8);
    headerRow.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF2563EB' }
      };
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
    });

    // 5. Style the Data Cells (Alignment Logic)
    worksheet.eachRow((row, rowNumber) => {
      if (rowNumber > 8 && rowNumber <= 8 + data.length) {
        row.eachCell((cell) => {
          cell.border = {
            top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
            left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
            bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
            right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
          };

          // Center-align numbers, percentages, and currencies
          const val = String(cell.value || '');
          const isNumeric = !isNaN(Number(cell.value)) || val.includes('%') || val.includes('₱');

          cell.alignment = {
            vertical: 'middle',
            horizontal: isNumeric ? 'center' : 'left',
            indent: isNumeric ? 0 : 1 // Slight indent for text
          };

          if (rowNumber % 2 === 0) {
            cell.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'FFF8FAFC' }
            };
          }
        });
      }
    });

    // 6. Add Signature Footer
    const footerStart = 8 + data.length + 3;
    worksheet.getRow(footerStart).values = ['--------------------------------------------------'];
    worksheet.getRow(footerStart + 1).values = ['Authorized Signature'];
    worksheet.getRow(footerStart + 2).values = [`${user?.first_name} ${user?.last_name}`];
    worksheet.getRow(footerStart + 3).values = ['JVD Events & Travel Management Co.'];

    for (let i = 0; i < 4; i++) {
      worksheet.getRow(footerStart + i).getCell(1).font = { size: 9, color: { argb: 'FF64748B' } };
    }

    // 7. Protection (Make headers non-editable)
    // Lock all cells by default, then unlock if needed. 
    // Here we just protect the sheet to make it professional.
    await worksheet.protect('jvd-secure', {
      selectLockedCells: true,
      selectUnlockedCells: true,
    });

    // 8. Generate and Save
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${title.toLowerCase().replace(/\s+/g, '_')}_report.xlsx`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  if (!user) return null;

  const DownloadActions = ({ title, data }: { title: string; data: any[] }) => {
    const [isOpen, setIsOpen] = useState(false);

    return (
      <div
        className="relative flex items-center"
        onMouseEnter={() => setIsOpen(true)}
        onMouseLeave={() => setIsOpen(false)}
      >
        <button
          onClick={(e) => { e.stopPropagation(); setIsOpen(!isOpen); }}
          className="p-2 hover:bg-slate-50 text-gray-400 hover:text-blue-600 rounded-xl transition-all opacity-0 group-hover:opacity-100"
        >
          <LuDownload className="w-4 h-4" />
        </button>

        {isOpen && (
          <div className="absolute top-full right-0 pt-2 z-[100]">
            <div className="w-32 bg-white rounded-2xl shadow-2xl border border-gray-100 py-2">
              <button
                onClick={(e) => { e.stopPropagation(); exportToPDF(title, data); setIsOpen(false); }}
                className="w-full px-4 py-2 text-left text-[10px] font-bold text-gray-600 hover:bg-red-50 hover:text-red-600 flex items-center gap-2 transition-colors"
              >
                <LuFileText className="w-3.5 h-3.5" />
                Export PDF
              </button>
              <button
                onClick={(e) => { e.stopPropagation(); exportToExcel(title, data); setIsOpen(false); }}
                className="w-full px-4 py-2 text-left text-[10px] font-bold text-gray-600 hover:bg-emerald-50 hover:text-emerald-600 flex items-center gap-2 transition-colors"
              >
                <LuFileSpreadsheet className="w-3.5 h-3.5" />
                Export Excel
              </button>
            </div>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="space-y-10 pb-12 pt-4">
      {/* Top Row: Global KPIs */}
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">
        {/* Total Employees */}
        <div className="bg-white dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm p-6 flex flex-col gap-4 hover:shadow-xl transition-all group relative">
          <div className="flex items-start justify-between">
            <div className="w-12 h-12 rounded-2xl bg-blue-500 flex items-center justify-center text-white shadow-lg shadow-blue-200 group-hover:scale-110 transition-transform">
              <LuUsers className="w-6 h-6" />
            </div>
            <div className="flex flex-col items-end gap-2">
              <div className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-600 flex items-center gap-1">
                <LuArrowUpRight className="w-3 h-3" />
                +12%
              </div>
              <DownloadActions title="Global Personnel" data={[{ Category: 'Total Employees', Value: 234, Growth: '+12%', Timestamp: new Date().toISOString() }]} />
            </div>
          </div>
          <div>
            <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-1">Total Employees</p>
            <p className="text-3xl font-black text-gray-900 dark:text-white">234</p>
          </div>
        </div>

        {/* Monthly Revenue */}
        <div className="bg-white dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm p-6 flex flex-col gap-4 hover:shadow-xl transition-all group">
          <div className="flex items-start justify-between">
            <div className="w-12 h-12 rounded-2xl bg-emerald-500 flex items-center justify-center text-white shadow-lg shadow-emerald-200 group-hover:scale-110 transition-transform">
              <LuDollarSign className="w-6 h-6" />
            </div>
            <div className="flex flex-col items-end gap-2">
              <div className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-600 flex items-center gap-1">
                <LuArrowUpRight className="w-3 h-3" />
                +8%
              </div>
              <DownloadActions title="Revenue Metrics" data={[{ Category: 'Monthly Revenue', Value: '₱2.3M', Growth: '+8%', Timestamp: new Date().toISOString() }]} />
            </div>
          </div>
          <div>
            <p className="text-3xl font-black text-gray-900 dark:text-white">₱2,300,000.00</p>
          </div>
        </div>

        {/* Active Agents */}
        <div className="bg-white dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm p-6 flex flex-col gap-4 hover:shadow-xl transition-all group">
          <div className="flex items-start justify-between">
            <div className="w-12 h-12 rounded-2xl bg-violet-500 flex items-center justify-center text-white shadow-lg shadow-violet-200 group-hover:scale-110 transition-transform">
              <LuActivity className="w-6 h-6" />
            </div>
            <div className="flex flex-col items-end gap-2">
              <div className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-600 flex items-center gap-1">
                <LuArrowUpRight className="w-3 h-3" />
                +5%
              </div>
              <DownloadActions title="Agent Activity" data={[{ Category: 'Active Agents', Value: 89, Growth: '+5%', Timestamp: new Date().toISOString() }]} />
            </div>
          </div>
          <div>
            <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-1">Active Agents</p>
            <p className="text-3xl font-black text-gray-900 dark:text-white">89</p>
          </div>
        </div>

        {/* Total Customers */}
        <div className="bg-white dark:bg-gray-900 rounded-[2rem] border border-gray-100 dark:border-gray-800 shadow-sm p-6 flex flex-col gap-4 hover:shadow-xl transition-all group">
          <div className="flex items-start justify-between">
            <div className="w-12 h-12 rounded-2xl bg-orange-500 flex items-center justify-center text-white shadow-lg shadow-orange-200 group-hover:scale-110 transition-transform">
              <LuGlobe className="w-6 h-6" />
            </div>
            <div className="flex flex-col items-end gap-2">
              <div className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-emerald-50 text-emerald-600 flex items-center gap-1">
                <LuArrowUpRight className="w-3 h-3" />
                +15%
              </div>
              <DownloadActions title="Customer Base" data={[{ Category: 'Total Customers', Value: 1456, Growth: '+15%', Timestamp: new Date().toISOString() }]} />
            </div>
          </div>
          <div>
            <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest mb-1">Total Customers</p>
            <p className="text-3xl font-black text-gray-900 dark:text-white">1,456</p>
          </div>
        </div>
      </div>

      {/* Main Performance Graph */}
      <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] border border-gray-100 dark:border-gray-800 shadow-sm p-8 group">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 gap-4">
          <div>
            <div className="flex items-center gap-3">
              <h2 className="text-xl font-black text-gray-900 dark:text-white tracking-tight">System Performance</h2>
              <DownloadActions title="System Performance Summary" data={mainChartData[activeFilter]} />
            </div>
            <p className="text-xs text-gray-400 font-medium mt-1">Consolidated revenue overview in Millions (PHP)</p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <div className="flex bg-slate-50 dark:bg-gray-800/50 p-1.5 rounded-2xl border border-slate-100 dark:border-gray-700/50">
              {(['Day', 'Week', 'Month', 'Year'] as const).map((filter) => (
                <button
                  key={filter}
                  onClick={() => setActiveFilter(filter)}
                  className={`px-4 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all ${activeFilter === filter
                    ? 'bg-white dark:bg-gray-700 text-blue-600 dark:text-blue-400 shadow-sm ring-1 ring-slate-200/50 dark:ring-gray-600'
                    : 'text-gray-400 hover:text-gray-600 dark:hover:text-gray-200'
                    }`}
                >
                  {filter}
                </button>
              ))}
            </div>
            <div className="flex items-center gap-2 px-3">
              <div className="w-3 h-3 rounded-full bg-blue-500" />
              <span className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Revenue</span>
            </div>
          </div>
        </div>

        <div className="h-[300px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={mainChartData[activeFilter]} key={activeFilter + theme}>
              <defs>
                <linearGradient id="colorMain" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.1} />
                  <stop offset="95%" stopColor="#3b82f6" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={theme === 'dark' ? '#334155' : '#f1f5f9'} />
              <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fontWeight: 700, fill: theme === 'dark' ? '#64748b' : '#94a3b8' }} dy={10} />
              <YAxis
                axisLine={false}
                tickLine={false}
                tick={{ fontSize: 10, fontWeight: 700, fill: theme === 'dark' ? '#64748b' : '#94a3b8' }}
                domain={[0, 'auto']}
                tickFormatter={(value) => {
                  if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`;
                  if (value >= 1000) return `${(value / 1000)}K`;
                  return value;
                }}
              />
              <Tooltip
                contentStyle={{ 
                  borderRadius: '24px', 
                  border: 'none', 
                  boxShadow: '0 25px 50px -12px rgb(0 0 0 / 0.15)',
                  backgroundColor: theme === 'dark' ? '#0f172a' : '#ffffff',
                  color: theme === 'dark' ? '#ffffff' : '#1e293b'
                }}
                itemStyle={{ color: theme === 'dark' ? '#60a5fa' : '#3b82f6' }}
                labelStyle={{ fontWeight: 800, color: theme === 'dark' ? '#ffffff' : '#1e293b' }}
                formatter={(value: any) => [`₱${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, 'Revenue']}
              />
              <Area
                type="monotone"
                dataKey="revenue"
                stroke="#3b82f6"
                strokeWidth={4}
                fillOpacity={1}
                fill="url(#colorMain)"
                animationDuration={800}
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Branch Specific Grid */}
      <h3 className="text-xs font-black text-gray-400 uppercase tracking-[0.3em] px-2">Branch Performance Matrix</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">
        {/* Accounting Branch */}
        <div className="bg-white dark:bg-gray-900 p-6 rounded-[2.5rem] border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-2xl transition-all group cursor-pointer relative" onClick={() => navigate('/accounting/billing')}>
          <div className="flex items-center justify-between mb-6">
            <div className="p-3 bg-emerald-50 dark:bg-emerald-950/30 text-emerald-600 dark:text-emerald-400 rounded-2xl group-hover:scale-110 transition-transform">
              <LuDollarSign className="w-6 h-6" />
            </div>
            <div className="text-right flex flex-col items-end">
              <p className="text-xl font-black text-gray-900 dark:text-white">₱4,200,000.00</p>
              <DownloadActions title="Accounting Branch Report" data={branchData.accounting} />
            </div>
          </div>
          <div className="h-20 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={branchData.accounting}>
                <Bar dataKey="value" fill="#10b981" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Procurement Branch */}
        <div className="bg-white p-6 rounded-[2.5rem] border border-gray-100 shadow-sm hover:shadow-2xl transition-all group cursor-pointer relative" onClick={() => navigate('/procurement/purchase-orders')}>
          <div className="flex items-center justify-between mb-6">
            <div className="p-3 bg-blue-50 text-blue-600 rounded-2xl group-hover:scale-110 transition-transform">
              <LuShoppingCart className="w-6 h-6" />
            </div>
            <div className="text-right flex flex-col items-end">
              <p className="text-[10px] font-black text-blue-600 uppercase tracking-tighter">Procurement</p>
              <p className="text-xl font-black text-gray-900">142 POs</p>
              <DownloadActions title="Procurement Branch Report" data={branchData.procurement} />
            </div>
          </div>
          <div className="h-20 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={branchData.procurement}>
                <Area type="monotone" dataKey="value" stroke="#3b82f6" fill="#dbeafe" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Inventory Branch */}
        <div className="bg-white p-6 rounded-[2.5rem] border border-gray-100 shadow-sm hover:shadow-2xl transition-all group cursor-pointer relative" onClick={() => navigate('/inventory/supplies')}>
          <div className="flex items-center justify-between mb-6">
            <div className="p-3 bg-indigo-50 text-indigo-600 rounded-2xl group-hover:scale-110 transition-transform">
              <LuPackage className="w-6 h-6" />
            </div>
            <div className="text-right flex flex-col items-end">
              <p className="text-[10px] font-black text-indigo-600 uppercase tracking-tighter">Inventory</p>
              <p className="text-xl font-black text-gray-900">92% Stock</p>
              <DownloadActions title="Inventory Branch Report" data={branchData.inventory} />
            </div>
          </div>
          <div className="h-20 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={branchData.inventory}>
                <Line type="stepAfter" dataKey="value" stroke="#6366f1" strokeWidth={3} dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Travel Branch */}
        <div className="bg-white p-6 rounded-[2.5rem] border border-gray-100 shadow-sm hover:shadow-2xl transition-all group cursor-pointer relative" onClick={() => navigate('/travel/customers')}>
          <div className="flex items-center justify-between mb-6">
            <div className="p-3 bg-rose-50 text-rose-600 rounded-2xl group-hover:scale-110 transition-transform">
              <LuGlobe className="w-6 h-6" />
            </div>
            <div className="text-right flex flex-col items-end">
              <p className="text-[10px] font-black text-rose-600 uppercase tracking-tighter">Travel</p>
              <p className="text-xl font-black text-gray-900">24 Bookings</p>
              <DownloadActions title="Travel Branch Report" data={branchData.travel} />
            </div>
          </div>
          <div className="h-20 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={branchData.travel}>
                <Area type="basis" dataKey="value" stroke="#f43f5e" fill="#ffe4e6" strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Bottom Section: Recent Activity & Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Recent Activity */}
        <div className="lg:col-span-2 bg-white dark:bg-gray-900 rounded-[2.5rem] border border-gray-100 dark:border-gray-800 shadow-sm p-8 group relative">
          <div className="flex items-center justify-between mb-8">
            <div className="flex items-center gap-3">
              <h3 className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest">Recent Activity</h3>
              <DownloadActions
                title="Recent Operational Activity"
                data={[
                  { Action: 'Operation #1025', User: 'Admin', Status: 'Success', Timestamp: '2 hours ago' },
                  { Action: 'Operation #1026', User: 'HR', Status: 'Pending', Timestamp: '1 hour ago' },
                  { Action: 'Operation #1027', User: 'Accounting', Status: 'Success', Timestamp: '30 mins ago' },
                  { Action: 'Operation #1028', User: 'Agent', Status: 'Updated', Timestamp: 'Just now' },
                ]}
              />
            </div>
            <button className="text-[10px] font-bold text-blue-600 uppercase tracking-widest hover:underline transition-all">View Full Log</button>
          </div>
          <div className="space-y-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="flex items-center gap-4 group/item">
                <div className="w-10 h-10 rounded-xl bg-slate-50 dark:bg-gray-800 flex items-center justify-center text-slate-400 dark:text-gray-500 group-hover/item:bg-blue-50 dark:group-hover/item:bg-blue-900/30 group-hover/item:text-blue-600 transition-colors">
                  <LuCircle className="w-2.5 h-2.5 fill-current" />
                </div>
                <div className="flex-1 border-b border-gray-50 dark:border-gray-800 pb-4 group-last:border-0">
                  <p className="text-sm font-bold text-gray-800 dark:text-gray-200">Operational Update #{1024 + i}</p>
                  <p className="text-xs text-gray-400 mt-0.5">System synchronized with branch node {i}</p>
                </div>
                <span className="text-[10px] font-bold text-gray-300 uppercase tracking-tighter">2 hours ago</span>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white dark:bg-gray-900 rounded-[2.5rem] border border-gray-100 dark:border-gray-800 shadow-sm p-8">
          <div className="flex items-center justify-between mb-8 px-2">
            <h3 className="text-sm font-black text-gray-900 dark:text-white uppercase tracking-widest">Quick Actions</h3>
            <span className="text-[10px] font-black text-blue-600 bg-blue-50 px-2 py-0.5 rounded-lg uppercase tracking-tighter">System Fundamentals</span>
          </div>
          
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <button 
              onClick={() => navigate('/procurement/purchase-orders')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-blue-200 dark:hover:border-blue-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-blue-600 transition-colors">
                <LuFileText className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">New PO</span>
            </button>

            <button 
              onClick={() => navigate('/procurement/job-orders')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-emerald-200 dark:hover:border-emerald-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-emerald-600 transition-colors">
                <LuClipboardList className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">Job Order</span>
            </button>

            <button 
              onClick={() => navigate('/accounting/pos')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-pink-200 dark:hover:border-pink-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-pink-600 transition-colors">
                <LuReceipt className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">POS</span>
            </button>

            <button 
              onClick={() => navigate('/travel/customers')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-blue-200 dark:hover:border-blue-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-blue-600 transition-colors">
                <LuUsers className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">Customers</span>
            </button>

            <button 
              onClick={() => navigate('/hr/employees')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-purple-200 dark:hover:border-purple-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-purple-600 transition-colors">
                <LuCircleUser className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">Employees</span>
            </button>

            <button 
              onClick={() => navigate('/inventory/fleet')}
              className="flex flex-col items-center justify-center gap-3 p-4 rounded-3xl bg-slate-50 dark:bg-gray-800 border border-slate-100 dark:border-gray-700 hover:border-indigo-200 dark:hover:border-indigo-800 hover:bg-white dark:hover:bg-gray-900 hover:shadow-lg transition-all group"
            >
              <div className="p-3 rounded-2xl bg-white dark:bg-gray-700 shadow-sm text-slate-400 group-hover:text-indigo-600 transition-colors">
                <LuBus className="w-5 h-5" />
              </div>
              <span className="text-[9px] font-bold text-gray-500 uppercase tracking-wider text-center">Fleet</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
