<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PublicRequestActionController extends Controller
{
    /**
     * Safely handle links generated by releases that allowed email actions.
     *
     * A GET request must never approve, reject, verify, or otherwise mutate a
     * business record. Valid legacy links are reduced to navigation hints and
     * sent to the authenticated application where the existing POST/PUT action
     * requires a current user, completed password setup, verified 2FA and the
     * workflow's role/ability checks.
     */
    public function handle(Request $request): RedirectResponse|View
    {
        if (!$request->hasValidSignature()) {
            return view('action_result', [
                'status' => 'error',
                'title' => 'Security Verification Failed',
                'message' => 'This legacy review link is invalid, tampered with, or expired. Sign in to the JVD Management System and open the approval queue directly.',
                'details' => [
                    'Error Code' => 'SEC_URL_INVALID_OR_EXPIRED',
                    'Record Changed' => 'No',
                ],
            ]);
        }

        $modelType = (string) $request->query('model_type', '');
        $modelId = max(0, (int) $request->query('model_id', 0));

        $reviewPath = match ($modelType) {
            'purchase_order' => '/procurement/purchase-orders',
            'cash_budget' => '/accounting/cash-budgets',
            'work_order' => '/procurement/work-orders',
            default => '/dashboard',
        };

        $query = $modelId > 0
            ? '?' . http_build_query(['review_type' => $modelType, 'review_id' => $modelId])
            : '';

        return redirect()->away(
            rtrim((string) config('app.frontend_url'), '/') . $reviewPath . $query
        );
    }
}
